
CREATE TABLE ChucVu
(
    maCV CHAR(10) not null,
    tenChucVu NVARCHAR2(30) not null,
    PRIMARY KEY (maCV)
);
CREATE TABLE NhanVien
(
    maNV INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY not null,
    HoTenNV NVARCHAR2(50) NOT NULL,
    maCV CHAR(10) NOT NULL,
    SdtNV VARCHAR(12),
    DiaChiNV NVARCHAR2(50),
    FOREIGN KEY (maCV) REFERENCES ChucVu(maCV)
);
CREATE TABLE KhachHang
(
    maKH INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    HoTenKH NVARCHAR2(50) NOT NULL,
    GioiTinh INT  NULL,
    CCCD INT  NULL,
    sdtKH VARCHAR(12)  NULL,
    EmailKH NVARCHAR2(50)  NULL,
    DiaChiKH NVARCHAR2(100)  NULL
);
CREATE TABLE LoaiPhong
(
    maLoaiPH INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    TenLoaiPH NVARCHAR2(50) NOT NULL,
    TienNghiPH NVARCHAR2(100)  NULL,
    GiaPH INT  NULL,
    SoKhachToiDa INT NULL
);
CREATE TABLE TrangThaiPH 
(
    maTrangThaiPH INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    trangThai NVARCHAR2(30) NOT NULL
);
CREATE TABLE Phong
(
  maPH INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
  TenPH NVARCHAR2(50) NOT NULL,
  maLoaiPH INT NOT NULL,
  maTrangThaiPH INT NOT NULL,
  ThongTinPH NVARCHAR2(100)  NULL,
  FOREIGN KEY (maLoaiPH) REFERENCES LoaiPhong(maLoaiPH),
  FOREIGN KEY (maTrangThaiPH) REFERENCES TrangThaiPH(maTrangThaiPH)
);
CREATE TABLE TinhTrangPDP
(
  maTTPDP INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
  TinhTrang NVARCHAR2(30) NOT NULL
);
CREATE TABLE PhieuDatPhong
(
    maPDP INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NgayLapPDP DATE NULL,
    maPH INT NOT NULL,
    maKH INT NOT NULL,
    FOREIGN KEY (maPH) REFERENCES Phong(maPH),
    FOREIGN KEY (maKH) REFERENCES KhachHang(maKH)
);


CREATE TABLE ChiTietPDP
(
    maPDP INT NOT NULL,
    maPH INT NOT NULL,
    NgayNhanPhong DATE  NULL,
    NgayTraPhong DATE  NULL,
    TinhTrang INT NOT NULL,
    PRIMARY KEY (maPDP, maPH),
    FOREIGN KEY (maPDP) REFERENCES PhieuDatPhong(maPDP),
    FOREIGN KEY (TinhTrang) REFERENCES TinhTrangPDP(maTTPDP),
    FOREIGN KEY (maPH) REFERENCES Phong(maPH)
);
CREATE TABLE HoaDon
(
    maHD INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NgayLapHD DATE  NULL,
    maNV INT NOT NULL,
    maPDP INT NOT NULL,
    maKH INT NOT NULL,
    TinhTrang NVARCHAR2(30) NOT NULL,
    TienPhong INT NULL,
    TongHoaDon INT NULL,
    FOREIGN KEY (maNV) REFERENCES NhanVien(maNV),
    FOREIGN KEY (maKH) REFERENCES KhachHang(maKH),
    FOREIGN KEY (maPDP) REFERENCES PhieuDatPhong(maPDP)
);

------------------------------------------------------------------------------------------------------
--BEGIN
--    FOR r IN (SELECT table_name FROM user_tables) LOOP
--        EXECUTE IMMEDIATE 'DROP TABLE "' || r.table_name || '" CASCADE CONSTRAINTS';
--    END LOOP;
--END;
---------------------------------------------------------

--B?ng ch?c v?
insert into ChucVu values('GD',N'Giám ??c');
insert into ChucVu values('TP',N'Tr??ng phòng');
insert into ChucVu values('NV',N'Nhân Viên');
select * from ChucVu;

--B?ng nhân viên
insert into NhanVien (HoTenNV, maCV, SdtNV, DiaChiNV) values (N'Lê ??c Phúc', 'GD', N'11211386784', N'123 Trung chánh, Nhà bè');
insert into NhanVien (HoTenNV, maCV, SdtNV, DiaChiNV) values (N'V? ??c Nam', 'TP', N'0367590203', N'T?ng 72, tòa nhà LandMark, Qu?n 3');
insert into NhanVien (HoTenNV, maCV, SdtNV, DiaChiNV) values (N'Nguy?n H?u Th?', 'NV',N'0836447006',N'???ng 14, ???ng ?i?n biên ph?, Qu?n 3');
insert into NhanVien (HoTenNV, maCV, SdtNV, DiaChiNV) values (N'Nguy?n Nh?t Ti?n', 'NV', N'0834472341', N'???ng 69/2,???ng cách m?ng tháng 8 , Qu?n 3');
select * from NhanVien;

--B?ng KhachHang
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Germana Robbins', 0, '068345276664', '0488813510', 'germanarobbins@gmail.com', '583 4th Park');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Alisha Southeran', 0, '095324671023', '0804626871', 'alishasoutheran@gmail.com', '331 Summit Plaza');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Alejandrina Firbank', 0, '047724201341', '0821032395', 'alejandrinafirbank@gmail.com', '8147 Esch Way');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Timoteo Lemmer', 0, '013901965165', '0724956489', 'timoteolemmer@gmail.com', '485 Summer Ridge Avenue');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Bartolomeo Meiklam', 0, '057718352999', '0462174401', 'bartolomeomeiklam@gmail.com', '02 Lyons Drive');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Filberto Dreye', 0, '035467867674', '0811090819', 'filbertodreye@gmail.com', '8163 Lukken Point');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Midge Mongin', 1, '090895859957', '0091569565', 'midgemongin@gmail.com', '75338 South Road');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Reiko Glidden', 1, '046468122812', '0711512167', 'reikoglidden@gmail.com', '54 Heffernan Terrace');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Brigham Lammenga', 1, '073822780291', '0420480964', 'brighamlammenga@gmail.com', '579 Del Mar Court');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Morganne Bullas', 1, '021220026382', '0484380779', 'morgannebullas@gmail.com', '00740 Columbus Parkway');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Ad Monck', 0, '071202773946', '0123396310', 'admonck@gmail.com', '2 Amoth Circle');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Malorie Tomasutti', 1, '089902402548', '0527718718', 'malorietomasutti@gmail.com', '00617 David Hill');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Alfy Gulvin', 0, '027487704056', '0603432282', 'alfygulvin@gmail.com', '671 Oak Center');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Robbert Stapylton', 0, '029736077980', '0207275852', 'robbertstapylton@gmail.com', '04732 Scofield Pass');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Forester Cockburn', 0, '022891668419', '0300579964', 'forestercockburn@gmail.com', '38640 Comanche Park');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Bart Cowland', 1, '025028394817', '0882231090', 'bartcowland@gmail.com', '9 Dorton Plaza');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Savina Loggie', 1, '038441468026', '0586714161', 'savinaloggie@gmail.com', '1815 Jackson Drive');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Harley Bester', 0, '067201410540', '0244726332', 'harleybester@gmail.com', '0 Oneill Pass');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Miles Drover', 1, '005796911953', '0120456430', 'milesdrover@gmail.com', '61335 Schiller Place');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Fredia Radborne', 1, '026338833660', '0729157996', 'frediaradborne@gmail.com', '5317 Welch Hill');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Neddie Atton', 0, '079126691260', '0036855744', 'neddieatton@gmail.com', '5308 Redwing Road');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Chaddie Attiwill', 0, '083881437545', '0919924221', 'chaddieattiwill@gmail.com', '8586 International Crossing');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Rosamond De Ambrosis', 1, '029968001113', '0157641689', 'rosamonddeambrosis@gmail.com', '7 Dapin Drive');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Mirabelle Cattemull', 0, '077693206010', '0872852422', 'mirabellecattemull@gmail.com', '06 Grayhawk Trail');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Valene Moraleda', 1, '031323303298', '0768359367', 'valenemoraleda@gmail.com', '5 Bluejay Lane');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Krissy Harsum', 1, '078919389965', '0724087107', 'krissyharsum@gmail.com', '4562 Delladonna Terrace');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Misti Seifert', 0, '018032955426', '0497425296', 'mistiseifert@gmail.com', '07261 Sunfield Pass');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Corty Bethell', 0, '037339962462', '0307080791', 'cortybethell@gmail.com', '27288 Village Plaza');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Coralyn Stuchberry', 1, '042833147417', '0911178124', 'coralynstuchberry@gmail.com', '50 Melrose Court');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Corenda Volks', 1, '055009490025', '0313179642', 'corendavolks@gmail.com', '9 Mifflin Way');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Cloe Dorkens', 1, '036247215024', '0319664526', 'cloedorkens@gmail.com', '39098 Cardinal Alley');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Norah Stitch', 1, '059051042349', '0154386709', 'norahstitch@gmail.com', '72 Fisk Court');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Clea Lorrain', 0, '094718054519', '0839318744', 'clealorrain@gmail.com', '13803 Eagle Crest Street');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Shaine Farmar', 1, '090176592257', '0707149705', 'shainefarmar@gmail.com', '086 Novick Road');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Sheeree De La Hay', 0, '046087016546', '0760261089', 'sheereedelahay@gmail.com', '4363 Reinke Trail');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Neil Petrol', 0, '089886877482', '0770558740', 'neilpetrol@gmail.com', '388 Stone Corner Street');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Dacia Northall', 0, '028711109331', '0016692147', 'dacianorthall@gmail.com', '4 Hansons Point');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Benito Tugwell', 1, '065361668283', '0778449551', 'benitotugwell@gmail.com', '8 Dennis Center');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Linn Ibotson', 0, '063965302817', '0516072570', 'linnibotson@gmail.com', '76197 Elmside Plaza');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Kaine Shaw', 0, '085023551797', '0333312626', 'kaineshaw@gmail.com', '47 Fallview Terrace');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Tiffie Klimuk', 1, '047190076444', '0552881466', 'tiffieklimuk@gmail.com', '68 Stuart Place');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Ignacius Aukland', 1, '019378930576', '0009473699', 'ignaciusaukland@gmail.com', '032 Arapahoe Terrace');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Nap Stoakley', 0, '093565666670', '0886960833', 'napstoakley@gmail.com', '732 West Pass');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Myca Grieg', 1, '098053788402', '0164795088', 'mycagrieg@gmail.com', '405 Gina Junction');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Damien Nizet', 0, '074580343290', '0783470296', 'damiennizet@gmail.com', '56758 Hayes Court');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Emmaline Irlam', 1, '021112989744', '0359614619', 'emmalineirlam@gmail.com', '42 Tennessee Street');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Elise Danilyak', 0, '082629796881', '0454721479', 'elisedanilyak@gmail.com', '7 Ludington Junction');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Elspeth Ell', 1, '094305466588', '0664294913', 'elspethell@gmail.com', '62 Huxley Park');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Britt Willoughway', 1, '015768743295', '0654147447', 'brittwilloughway@gmail.com', '349 Cottonwood Parkway');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Tove Sandey', 0, '000422425498', '0456135981', 'tovesandey@gmail.com', '569 Vidon Plaza');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Rina Gionettitti', 1, '037411972224', '0008450088', 'rinagionettitti@gmail.com', '1 Killdeer Street');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Gothart Walles', 0, '004605159751', '0954433293', 'gothartwalles@gmail.com', '67980 David Park');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Fonsie Jearum', 0, '054476372806', '0660748703', 'fonsiejearum@gmail.com', '5 Clemons Trail');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Lynea Caves', 1, '011278806342', '0359128876', 'lyneacaves@gmail.com', '844 Forest Point');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Filberte Gofton', 0, '090654358221', '0598956519', 'filbertegofton@gmail.com', '63 Hallows Street');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Fidel Lempenny', 1, '049106684186', '0656439680', 'fidellempenny@gmail.com', '7255 Coolidge Road');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Bartlett Sunter', 0, '034188542312', '0631484647', 'bartlettsunter@gmail.com', '08 American Ash Lane');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Caro Clilverd', 1, '024638327259', '0533919518', 'caroclilverd@gmail.com', '019 Almo Hill');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Jaynell Wessel', 1, '003688805937', '0616869594', 'jaynellwessel@gmail.com', '33 Kipling Crossing');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Micheil Brightey', 0, '096172136404', '0040719175', 'micheilbrightey@gmail.com', '3442 Briar Crest Alley');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Marketa Paton', 0, '010027609752', '0456337731', 'marketapaton@gmail.com', '11 Florence Lane');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Eduardo Itscovitz', 1, '091763190207', '0298749799', 'eduardoitscovitz@gmail.com', '834 Gateway Circle');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Rich Klimochkin', 1, '076002655848', '0231257144', 'richklimochkin@gmail.com', '49 Kenwood Junction');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Paulette Hales', 0, '095949801119', '0275247875', 'paulettehales@gmail.com', '94 Pennsylvania Pass');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Hadleigh Pedlingham', 0, '019317273575', '0087309418', 'hadleighpedlingham@gmail.com', '876 Elgar Junction');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Even Onions', 0, '004798622657', '0436818181', 'evenonions@gmail.com', '0461 Annamark Plaza');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Rhea Goodhall', 1, '014967114397', '0392615672', 'rheagoodhall@gmail.com', '690 Holmberg Street');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Franz Rubinlicht', 0, '053745842956', '0431499833', 'franzrubinlicht@gmail.com', '45090 Redwing Place');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Orsa Grunbaum', 1, '065494886850', '0460566557', 'orsagrunbaum@gmail.com', '329 Arrowood Circle');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Conrade Shingler', 1, '044611095823', '0516320370', 'conradeshingler@gmail.com', '11 Scoville Hill');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Michaela Dono', 1, '006084066912', '0386599324', 'michaeladono@gmail.com', '60 Lakewood Gardens Crossing');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Rainer Mellhuish', 1, '008419042238', '0365651606', 'rainermellhuish@gmail.com', '5 Heath Road');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Tish Frankiewicz', 0, '017023241011', '0207820941', 'tishfrankiewicz@gmail.com', '1 Ludington Center');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Grata Sharvell', 1, '097728603888', '0338310939', 'gratasharvell@gmail.com', '9 Johnson Alley');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Marleen Piddle', 0, '014481443100', '0968173834', 'marleenpiddle@gmail.com', '66 Morningstar Court');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Parrnell Bather', 0, '068654830039', '0305222299', 'parrnellbather@gmail.com', '86 Bobwhite Parkway');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Melesa Vaisey', 1, '054442154671', '0174558963', 'melesavaisey@gmail.com', '5953 Lakewood Alley');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Viole Pawlowicz', 0, '019310169090', '0142146585', 'violepawlowicz@gmail.com', '052 Sunfield Terrace');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Garfield Jenne', 1, '031676751648', '0819406159', 'garfieldjenne@gmail.com', '3028 Maryland Crossing');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Marcella Luney', 1, '093843663997', '0583562769', 'marcellaluney@gmail.com', '811 Clarendon Drive');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Anastasie Keyhoe', 0, '060987305277', '0257196893', 'anastasiekeyhoe@gmail.com', '45 Maryland Lane');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Ilene Hunnicot', 1, '040092133885', '0703099948', 'ilenehunnicot@gmail.com', '1 Vermont Drive');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Sonni Sample', 0, '022757571880', '0831194331', 'sonnisample@gmail.com', '98323 Hagan Drive');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Terrance Noel', 0, '045371631385', '0259830513', 'terrancenoel@gmail.com', '36070 Calypso Place');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Gay Trahar', 0, '056386734093', '0905837624', 'gaytrahar@gmail.com', '75054 Hallows Place');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Gardener Hammell', 1, '021466630655', '0631215106', 'gardenerhammell@gmail.com', '38 4th Road');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Doretta Verry', 0, '092841894275', '0376870909', 'dorettaverry@gmail.com', '084 Del Sol Hill');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Maurits Fusco', 0, '050503834870', '0618213914', 'mauritsfusco@gmail.com', '379 Buell Avenue');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Samaria Beggi', 1, '016440662087', '0404189722', 'samariabeggi@gmail.com', '37 David Alley');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Mahalia Aymes', 1, '043834888339', '0268075862', 'mahaliaaymes@gmail.com', '89885 New Castle Center');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Celestia Blofeld', 0, '071406109972', '0639589093', 'celestiablofeld@gmail.com', '540 Spenser Parkway');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Jorgan Lancashire', 0, '034752433650', '0598884251', 'jorganlancashire@gmail.com', '613 Superior Point');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Devland McKall', 0, '023390079375', '0655259122', 'devlandmckall@gmail.com', '26759 Hovde Road');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Gennie Gosswell', 1, '057967934800', '0457742791', 'genniegosswell@gmail.com', '9 Buell Junction');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Gilli Kenealy', 1, '070704505862', '0236533893', 'gillikenealy@gmail.com', '9619 Summer Ridge Park');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Vilma Dewey', 0, '065171938857', '0941582103', 'vilmadewey@gmail.com', '57 Elmside Circle');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Goran Chiommienti', 1, '062983862920', '0445592860', 'goranchiommienti@gmail.com', '907 Thompson Avenue');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Greg Johansson', 1, '064617635543', '0642297198', 'gregjohansson@gmail.com', '908 Muir Alley');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Alyssa Sigsworth', 0, '039481049877', '0906243719', 'alyssasigsworth@gmail.com', '4754 Sommers Crossing');
insert into KhachHang (hotenkh, gioitinh, cccd, sdtkh, emailkh, diachikh) values ('Leanora Tollady', 0, '034453535472', '0290937275', 'leanoratollady@gmail.com', '3457 Southridge Drive');
select * from KhachHang;

--B?ng LoaiPhong
insert into LoaiPhong (TenLoaiPH,TienNghiPH,GiaPH,SoKhachToiDa) values (N'Phòng vip', N'Phòng vip sang, x?n, m?n', 1000000, 2);
insert into LoaiPhong (TenLoaiPH,TienNghiPH,GiaPH,SoKhachToiDa) values (N'Phòng th??ng', N'Phòng th??ng giá r?', 5000000, 3);
insert into LoaiPhong (TenLoaiPH,TienNghiPH,GiaPH,SoKhachToiDa) values (N'Phòng gia ?ình', N'Phòng gia ?ình ti?n l?i thoáng mát', 10000000, 5);
select * from LoaiPhong;
 
--B?ng TrangThaiPH
insert into TrangThaiPH (trangThai) values (N'Còn tr?ng');
insert into TrangThaiPH (trangThai) values (N'H?t phòng');
insert into TrangThaiPH (trangThai) values (N'?ang s? d?ng');  
select * from TrangThaiPH;

--B?ng Phong (m?c ??nh Còn tr?ng h?t)
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 1', 1, 1, N'1 máy l?nh, 2 TV, 2 gi??ng ??n');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 2', 2, 1, N'1 máy l?nh, 1 TV, 1 gi??ng ??n');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 3', 3, 1, N'2 máy l?nh, 2 TV, 1 gi??ng ?ôi, 2 gi??ng ??n, 2 nhà t?m');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 4', 2, 1, N'1 máy l?nh, 1 TV, 2 gi??ng ??n');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 5', 1, 1, N'1 máy l?nh, 2 TV, 2 gi??ng ??n');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 6', 1, 1, N'1 máy l?nh, 1 TV, 1 gi??ng ?ôi');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 7', 3, 1, N'2 máy l?nh, 2 TV, 1 gi??ng ?ôi, 2 gi??ng ??n, 2 nhà t?m');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 8', 1, 1, N'1 máy l?nh, 2 TV, 2 gi??ng ??n');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 9', 1, 1, N'1 máy l?nh, 2 TV, 2 gi??ng ??n');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 10', 2, 1, N'1 máy l?nh, 1 TV, 1 gi??ng ??n');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 11', 3, 1, N'2 máy l?nh, 2 TV, 1 gi??ng ?ôi, 2 gi??ng ??n, 2 nhà t?m');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 12', 3, 1, N'2 máy l?nh, 2 TV, 1 gi??ng ?ôi, 2 gi??ng ??n, 2 nhà t?m');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 13', 3, 1, N'2 máy l?nh, 2 TV, 1 gi??ng ?ôi, 2 gi??ng ??n, 2 nhà t?m');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 14', 3, 1, N'2 máy l?nh, 2 TV, 1 gi??ng ?ôi, 2 gi??ng ??n, 2 nhà t?m');
insert into Phong (tenph, maloaiph, matrangthaiph, thongtinph) values (N'Phòng 15', 1, 1, N'1 máy l?nh, 1 TV, 1 gi??ng ?ôi');
select * from Phong;

--B?ng PhieuDatPhong
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-03-18 12:37:33', 14, 71);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-03-27 11:10:24', 13, 13);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-02-09 07:54:00', 9, 97);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-03-05 07:01:45', 9, 42);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-02-12 22:54:28', 14, 75);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-02-10 15:36:36', 13, 88);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-03-30 07:32:18', 11, 67);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-02-09 04:55:28', 6, 46);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-02-14 21:23:50', 15, 85);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-03-05 05:24:29', 11, 60);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-02-20 22:48:38', 11, 19);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-03-13 21:04:22', 12, 77);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-02-26 18:44:07', 7, 69);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-02-19 06:41:28', 8, 9);
insert into PhieuDatPhong (ngaylappdp, maph, makh) values ('2024-03-23 08:04:19', 9, 73);
select * from PhieuDatPhong;




--B?ng TinhTrangPDP
insert into TinhTrangPDP (TinhTrang) values (N'?ang ??t'); 
insert into TinhTrangPDP (TinhTrang) values (N'?ã xong');
insert into TinhTrangPDP (TinhTrang) values (N'?ã h?y');
insert into TinhTrangPDP (TinhTrang) values (N'?ã thanh toán');
select * from TinhTrangPDP;

--B?ng ChiTietPDP

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';



insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (55, 1, '2024-02-04 17:49:41', '2024-05-11 17:40:55', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (56, 2, '2024-02-27 08:47:34', '2024-04-16 08:00:21', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (57, 3, '2024-02-20 04:27:33', '2024-05-05 15:51:08', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (59, 3, '2024-02-02 11:03:57', '2024-05-08 04:06:27', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (60, 5, '2024-03-28 22:26:07', '2024-05-24 21:22:32', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (61, 6, '2024-03-14 06:06:50', '2024-04-30 09:29:24', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (61, 7, '2024-03-03 17:18:38', '2024-05-24 19:04:14', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (62, 9, '2024-02-08 20:16:22', '2024-05-17 20:57:48', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (63, 10, '2024-03-30 04:24:07', '2024-04-21 12:09:40', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (64, 10, '2024-02-03 06:01:54', '2024-05-24 21:01:36', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (65, 11, '2024-03-25 02:11:49', '2024-04-09 23:57:55', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (66, 12, '2024-02-17 05:03:46', '2024-04-06 05:02:19', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (67, 13, '2024-03-02 19:12:16', '2024-05-08 15:01:17', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (67, 14, '2024-02-17 09:16:53', '2024-05-12 03:12:27', 1);
insert into ChiTietPDP (mapdp, maph, ngaynhanphong, ngaytraphong, tinhtrang) values (68, 15, '2024-03-16 08:08:26', '2024-05-14 07:40:37', 1);
select * from ChiTietPDP;

--B?ng HoaDon
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-05-19 20:27:46', 1, 61, 9, '?ã Thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-05-13 18:35:41', 1, 62, 2, 'Ch?a thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-04-16 04:51:37', 4, 63, 14, '?ã Thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-03-31 03:55:15', 3, 64, 15, 'Ch?a thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-03-18 09:07:35', 4, 65, 15, '?ã Thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-05-05 13:50:01', 4, 66, 14, '?ã Thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-05-05 21:17:10', 1, 67, 1, 'Ch?a thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-05-30 20:16:17', 3, 68, 11, '?ã Thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-05-30 23:42:07', 3, 64, 14, '?ã Thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-05-20 20:49:05', 2, 60, 4, '?ã Thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-03-07 13:00:24', 3, 61, 1, 'Ch?a thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-05-24 01:53:30', 4, 62, 10, '?ã Thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-04-16 06:27:13', 4, 63, 10, 'Ch?a thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-03-26 15:42:42', 1, 64, 2, 'Ch?a thanh toán', null, null);
insert into HoaDon (ngaylaphd, manv, mapdp, makh, tinhtrang, tienphong, tonghoadon) values ('2024-04-15 11:45:09', 2, 65, 10, '?ã Thanh toán', null, null);
select * from HoaDon;
----------------------------------------------------------------------
select * from ChucVu;
select * from NhanVien;
select * from KhachHang;
select * from LoaiPhong;
select * from TrangThaiPH;
select * from Phong;
select * from PhieuDatPhong;
select * from TinhTrangPDP;
select * from ChiTietPDP;
select * from HoaDon;


SET SERVEROUTPUT ON;


--SP1: “C?p nh?t tình tr?ng ??t phòng”
CREATE OR REPLACE PROCEDURE sp_CapNhatTinhTrangDatPhong(
    p_maPDP IN CHAR,
    p_maTTDP IN NUMBER
) AS
BEGIN
    UPDATE ChiTietPDP
    SET TINHTRANG = p_maTTDP
    WHERE MAPDP = p_maPDP;
END;

BEGIN
    sp_CapNhatTinhTrangDatPhong('55', 3);
END;



--SP3:”Tìm ki?m phòng theo tình tr?ng”
CREATE OR REPLACE PROCEDURE sp_SearchPhongByStatus(
    p_maTrangThai IN INT
) AS
BEGIN
    FOR r IN (SELECT * FROM Phong WHERE maTrangThaiPH = p_maTrangThai) LOOP
      
        DBMS_OUTPUT.PUT_LINE(r.TenPH || ' - ' || r.ThongTinPH);
    END LOOP;
END;

EXEC sp_SearchPhongByStatus(1);




-- SP4:”Tìm ki?m hóa ??n theo mã khách hàng”
CREATE OR REPLACE PROCEDURE sp_SearchHoaDonTheoKhachHang(
    p_maKH IN INT
) AS
BEGIN
    for r in (SELECT * FROM HoaDon  WHERE maKH = p_maKH) loop
    
    DBMS_OUTPUT.PUT_LINE(r.MAHD || '-' || r.TINHTRANG);  
    end loop;
END;

EXEC sp_SearchHoaDonTheoKhachHang(4);


-- SP5:’Thêm ch?c v? nhân viên m?i’
CREATE OR REPLACE PROCEDURE sp_AddChucVu(
    p_maCV IN CHAR,
    p_tenChucVu IN NVARCHAR2
) AS
BEGIN
    INSERT INTO ChucVu (maCV, tenChucVu) 
    VALUES (p_maCV, p_tenChucVu);
END;


BEGIN
    sp_AddChucVu('BV', N'Bao ve');
END;

select*from chucvu;

--SP6:’Thêm tr?ng thái phòng m?i’
CREATE OR REPLACE PROCEDURE AddTrangThaiPH(
    p_trangThai IN NVARCHAR2
) AS
BEGIN
    INSERT INTO TrangThaiPH (trangThai) 
    VALUES (p_trangThai);
END;

begin
    AddTrangThaiPH (N'S?n Sàng');
end;


select *from TrangThaiPH;





-- SP8:”C?p nh?t thông tin lo?i phòng”
CREATE OR REPLACE PROCEDURE UpdateLoaiPhong(
    p_maLoaiPH IN INT,
    p_TenLoaiPH IN NVARCHAR2,
    p_SoKhachToiDa IN INT
) AS
BEGIN
    UPDATE LoaiPhong
    SET TenLoaiPH = p_TenLoaiPH, SoKhachToiDa = p_SoKhachToiDa
    WHERE maLoaiPH = p_maLoaiPH;
END;

Begin
    UpdateLoaiPhong ('2', N'Deluxe', 3);
end;


select*from LoaiPhong;

